// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poipkkidkdlqfobtdaqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvaXBra2lka2RscWZvYnRkYXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzA4MjAsImV4cCI6MjA3MDA0NjgyMH0.P45tNfn0ypSHeL1HjFj4CkBKijaPi1zqYhIBCn5ex4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});